version: 2
jobs:
  build:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t fluffycat/ps4-waker-rest:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push fluffycat/ps4-waker-rest:latest