version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t fluffycat/ps4-waker-rest:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push fluffycat/ps4-waker-rest:latest